name: Deploy 2025RemakeDocs

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # needed to push to gh-pages
    defaults:
      run:
        working-directory: 2025RemakeDocs

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
          cache-dependency-path: 2025RemakeDocs/yarn.lock

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Configure Git identity
        run: |
          git config --global user.name "${{ secrets.GIT_USER }}"
          git config --global user.email "${{ secrets.GIT_USER }}@users.noreply.github.com"

      - name: Build & deploy docs
        env:
          GIT_USER: ${{ secrets.GIT_USER }}
          GIT_PASS: ${{ secrets.GIT_PASS }}
          USE_SSH: false
        run: yarn deploy
