name: Generate Latest PR Badge

on:
  schedule:
    - cron: "0 * * * *"  # every hour
  workflow_dispatch:

permissions:
  contents: write  # needed to push changes

jobs:
  badge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Fetch latest PR info
        run: |
          pr=$(gh pr list --limit 1 --json number,title --jq '.[] | "#\(.number): \(.title)"')
          echo "Latest PR: $pr"
          mkdir -p img
          echo '{
            "schemaVersion": 1,
            "label": "latest PR",
            "message": "'"$pr"'",
            "color": "blue"
          }' > img/latest-pr.json
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit badge to img/ folder
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@users.noreply.github.com'
          git pull
          git add img/latest-pr.json
          git commit -m "Update latest PR badge" || echo "No changes"
          git push
