name: Generate Latest PR Badge

on:
  schedule:
    - cron: "0 * * * *"  # every hour on the hour
  workflow_dispatch:

jobs:
  badge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Fetch latest PR info
        run: |
          pr=$(gh pr list --limit 1 --json number,title --jq '.[] | "#\(.number): \(.title)"')
          echo "Latest PR: $pr"
          mkdir -p img
          echo '{
            "schemaVersion": 1,
            "label": "latest PR",
            "message": "'"$pr"'",
            "color": "blue"
          }' > img/latest-pr.json
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload badge.json to img/
        uses: actions/upload-artifact@v4
        with:
          name: img
          path: img/latest-pr.json
          if-no-files-found: error
