name: Generate Latest PR Badge

on:
  schedule:
    - cron: "0 * * * *"    # every hour
  workflow_dispatch:

permissions:
  contents: write

jobs:
  badge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Fetch latest PR info
        run: |
          pr=$(gh pr list --limit 1 --state open --json number,title \
               --template '#{{.number}}: {{.title}}')
          echo "Latest PR is: $pr"

          mkdir -p img
          cat <<EOF > img/latest-pr.json
          {
            "schemaVersion": 1,
            "label": "latest PR",
            "message": "${pr}",
            "color": "blue"
          }
          EOF
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and push badge JSON
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add img/latest-pr.json
          git diff --quiet --exit-code || git commit -m "chore: update latest PR badge"
          git push
